# Site settings
title:          metterian blog
baseurl:        ""
description:    "ë‚´ì¼ì„ ê¸°ë¡í•˜ê¸° ìœ„í•´ì„œ ì˜¤ëŠ˜ì„ ê¸°ë¡í•©ë‹ˆë‹¤ ğŸ¤—"
url:            "https://github.metterian.io"

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X

# Author
author:
  name:         SeungJun Lee
  url:          https://github.metterian.io
  email:        dzzy6505gmail.com
  gitgub:       metterian

# Build settings
markdown:       kramdown
kramdown:
  syntax_hightlighter: rouge
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  highlighter: rouge
  lsi : false
  excerpt_separator: "\n\n"
  incremental: false






include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale


# Plugins
mathjax: true # whether support mathjax
